workflows:
  release-apk:
    name: Release APK Build
    environment:
      flutter: 3.38.1

    cache:
      cache_paths: []   # 🔥 Cache deaktiviert – Android wird vollständig neu gebaut!

    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build Release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - funatiker1968@gmail.com
