workflows:
  release-apk:
    name: Build Release APK
    environment:
      flutter: 3.38.1
    scripts:
      - name: Install packages
        script: |
          flutter pub get
      
      - name: Build release APK
        script: |
          flutter build apk --release
      
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
    publishing:
      email:
        recipients:
          - funatiker1968@gmail.com
