workflows:
  android-debug:
    name: Android Debug Build
    environment:
      flutter: 3.38.1
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      
      - name: Build debug APK (skip analysis)
        script: |
          # Direkter Build ohne Analyse
          flutter build apk --debug --no-analytics
      
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      
    publishing:
      email:
        recipients:
          - funatiker1968@gmail.com
      
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true
