workflows:
  android-debug:
    name: Android Debug Build
    environment:
      flutter: 3.38.1
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      
      - name: Build debug APK
        script: |
          # Einfacher Build ohne Analyse
          flutter build apk --debug
      
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      
    publishing:
      email:
        recipients:
          - funatiker1968@gmail.com
