workflows:
  debug-apk:
    name: Build Debug APK
    environment:
      flutter: 3.38.1
    scripts:
      - name: Install packages
        script: |
          flutter pub get
      
      - name: Build debug APK
        script: |
          flutter build apk --debug
      
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      
    publishing:
      email:
        recipients:
          - funatiker1968@gmail.com
